version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm test
workflow:
  version: 2
  install&test:
    jobs:
      - install
      - test:
        requires:
          - install
