export const GET_ERRORS = "GET_ERRORS";
export const REGISTER_USER = "REGISTER_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_PROFILES = "GET_PROFILES";
export const GET_PROFILE = "GET_PROFILE";
export const GET_GITHUB_REPOS = "GET_GITHUB_REPOS";
export const ADD_PROFILE = "ADD_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
